version: "3.1"
services:
  php:
    image: ricardopedias/docker-project:php82
    container_name: iquety-domain
    volumes:
      - .:/application
    networks:
      - iquety-domain-network
networks:
  iquety-domain-network:
    driver: bridge